### PR TITLE
Update penguin.js

### PR DESCRIPTION
**Pull request by Genko-H**
file not found

### CODE REVIEW

**Comment by RykerCohen** [comment]
What media server are you using for this to run

**Comment by Genko-H** [comment]
http://skihill.net/.repo

lun., 8 iun. 2020, 17:16 Ryker Cohen <notifications@github.com> a scris:

**Comment by RykerCohen** [comment]
The Legacy One? And what about the login page

**Comment by RykerCohen** [comment]
Or where are you placing the media server

**Comment by Adamb2019** [comment]
oop i forgot to remove that as i was testing something thanks

**Pull request merged**
